{
  config,
  pkgs,
  lib,
  ...
}: let
  customPkgs = import ../pkgs {inherit pkgs lib;};
in {
  environment.systemPackages = with pkgs; [
    # Applications
    brave # TODO: make a module to save browser stuff
    vesktop
    git
    nodejs
    wget
    curl
    tree
    gnumake
    gcc
    socat
    ffmpeg
    gnused
    gdb
    stdenv.cc.cc.lib
    nix-prefetch-git
    binutils
    hashcat
    cmake
    ninja
    pkg-config
    autoconf
    automake
    libtool
    gawk
    obs-studio
    lazygit
    jdk17
    bun
    maven
    gradle
    visualvm
    jdt-language-server
    python3Packages.pip
    (python310.withPackages (ps:
      with ps;
        [
          virtualenv
          ipython
          i3ipc
          xlib
          six
          psutil
          pynvml
          pyqtgraph
          pyqt6
          numpy
          pandas
          matplotlib
          scipy
          requests
          click
          typer
          rich
          pyyaml
          pytz
          onnxruntime
          pillow
          timm
        ]
        ++ [customPkgs.python-rembg]))
    uv
    ruff
    black
    htop
    btop
    nvtopPackages.full
    ripgrep
    fd
    fzf
    jq
    bash
    customPkgs.fish-rust
    go
    sqls
    deno
    redis
    cloudflared
    rustup
    cargo-edit
    cargo-watch
    cargo-outdated
    cargo-audit
    openssl
    openssl.dev
    pkg-config
    libxml2
    zlib
    ghc
    cabal-install
    stack
    haskell-language-server
    postgresql
    sqlite
    spotify
    git-lfs
    gitAndTools.gh
    gitAndTools.diff-so-fancy
    ani-cli
    yt-dlp
    nmap
    psmisc
    ugrep
    unzip
    starship
    flameshot
    yarn
    nodePackages.typescript-language-server
    nodePackages.eslint
    nodePackages.prettier
    nodePackages.vitest
    nodePackages.pg
    nodePackages.sqlite3
    httpie
    wrk
    nodePackages.pnpm
    zlib.dev
  ];
}
