{...}: {
  imports = [
    ../settings.nix
    ./cachix.nix
    ./modules/gtk.nix
    ./modules/audio.nix
    ./modules/bluetooth.nix
    ./modules/boot.nix
    ./modules/docker.nix
    ./modules/env.nix
    ./modules/fonts.nix
    ./modules/net.nix
    ./modules/nixos.nix
    ./modules/nvidia.nix
    ./modules/steam.nix
    ./modules/timezone.nix
    ./modules/user.nix
    ./modules/python.nix
    ./modules/npm.nix
    ./modules/tailscale.nix
    ./modules/ollama.nix
    ./modules/cups.nix
    ./modules/rust.nix
    ./modules/misc.nix
    ./modules/libs.nix
    ./modules/rgb.nix
    ./modules/hyprland.nix
    ./modules/searxng.nix
    ./modules/nano.nix
    ./modules/qt.nix
    ./modules/appimage.nix
    ./modules/greeter.nix
    ./modules/go.nix
    ./modules/flatpak.nix
    ./modules/aagl.nix
    ./modules/ssh.nix
    ./modules/sops.nix
    ./modules/udisk.nix
    ./modules/dms.nix
    ./modules/mullvad.nix
  ];
}
