{...}: {
  imports = [
    ./appimage.nix
    ./boot.nix
    ./docker.nix
    ./env.nix
    ./go.nix
    ./ld.nix
    ./libs.nix
    ./rust.nix
    ./nano.nix
    ./net.nix
    ./nixos.nix
    ./npm.nix
    ./python.nix
    ./searxng.nix
    ./sops.nix
    ./ssh.nix
    ./tailscale.nix
    ./timezone.nix
    ./user.nix
    ./aagl.nix
    ./audio.nix
    ./bluetooth.nix
    ./controller.nix
    ./cups.nix
    ./flatpak.nix
    ./greeter.nix
    ./hyprland.nix
    ./ld.nix
    ./libs.nix
    ./mullvad.nix
    ./net.nix
    ./ollama.nix
    ./rgb.nix
    ./steam.nix
    ./udisk.nix
    ./phone.nix
    ./fonts.nix
  ];
}
