{
  pkgs,
  config,
  lib,
  ...
}: {
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs;
      [
        glibc
        libarchive
        libglvnd
        mesa
        libdrm
        vulkan-loader
        libva
        wayland
        libxkbcommon
        libx11
        libxcb
        libxext
        libxrandr
        libxi
        libxcursor
        libxcomposite
        libxfixes
        libxinerama
        libxtst
        libxdamage
        libxshmfence
        libxrender
        libxscrnsaver
        libxcrypt
        libxcrypt-legacy
        libuuid
        libxcb-cursor
        libxcb-image
        libxcb-keysyms
        libxcb-render-util
        libxcb-wm
        freetype
        fontconfig
        harfbuzz
        icu
        sqlite
        expat
        libxslt
        pcre2
        ncurses
        readline
        glib
        dbus
        udev
        libffi
        libpng
        libjpeg
        alsa-lib
        libpulseaudio
        pipewire
        qt6.qtbase
        qt6.qtmultimedia
        qt6.qtdeclarative
        qt6.qtsvg
        qt6.qtwayland
        libsndfile
        SDL2
        sdl3
        openal
        ffmpeg
        libvdpau
        libGLU
        gtk3
        gtk4
        libadwaita
        libnotify
        libusb1
        libinput
        libevdev
        hidapi
        cairo
        pango
        gdk-pixbuf
        at-spi2-core
        openblas
        fuse3
        libelf
        elfutils
        nss
        nspr
        cups
        libsecret
        krb5
        keyutils
        libunwind
      ]
      ++ lib.optionals config.hardware.nvidia.modesetting.enable [
        config.hardware.nvidia.package
        cudaPackages.cudatoolkit
        cudaPackages.cudnn
        cudaPackages.nccl
      ];
  };
}
