{
  pkgs,
  config,
  lib,
  ...
}: {
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs;
      [
        glibc
        stdenv.cc.cc
        stdenv.cc.cc.lib
        libgcc.lib
        zlib
        zstd
        bzip2
        xz
        libglvnd
        mesa
        libdrm
        vulkan-loader
        libva
        vulkan-tools
        wayland
        wayland-protocols
        libxkbcommon
        libx11
        libxcb
        libxext
        libxrandr
        libxi
        libxcursor
        libxcomposite
        libxfixes
        libxinerama
        libxtst
        libxdamage
        libxshmfence
        libxrender
        libxcrypt
        libxcrypt-legacy
        libuuid
        libxcb-cursor
        libxcb-image
        libxcb-keysyms
        libxcb-render-util
        libxcb-wm
        freetype
        fontconfig
        harfbuzz
        icu
        openssl
        curl
        sqlite
        expat
        libxml2
        libxslt
        pcre2
        libsodium
        ncurses
        readline
        glib
        dbus
        systemd
        util-linux
        e2fsprogs
        attr
        acl
        alsa-lib
        libpulseaudio
        pipewire
        libsndfile
        SDL2
        sdl3
        openal
        ffmpeg
        libvdpau
        gtk3
        cairo
        pango
        gdk-pixbuf
        atk
        at-spi2-atk
        at-spi2-core
        openblas
        fuse3
        libelf
        elfutils
        nss
        nspr
        cups
        libsecret
        krb5
        keyutils
      ]
      ++ lib.optionals config.hardware.nvidia.modesetting.enable [
        config.hardware.nvidia.package
        cudaPackages.cudatoolkit
        cudaPackages.cudnn
        cudaPackages.nccl
      ];
  };
}